name: The Journey of Spirit
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: The Journey of Spirit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#374d75'
    - '#090909'
    - '#9091b6'
    - '#fbdb33'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
